version: '3.8'

services:
  bankana:
    build:
      context: .
      dockerfile: ./infra/bankana/Dockerfile
    container_name: bankana
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
